### ISSUE TITLE
你好，我运行代码的时候出现了这个错误：FileNotFoundError: [Errno 2] No such file or directory: 'models1005/model_nn_5ways_1shot4mag1001722seen.pkl'，请问是怎么一回事呢？

### ISSUE THREAD

**Issue by nancy-ux** [YifanDengWHU/META-DDIE#2]

**Comment by YifanDengWHU** [comment]
你好，应该是在读模型的时候产生了问题，你看一下具体是在哪一行的时候产生的问题呢？路径下面有这个名字的模型嘛？

**Comment by nancy-ux** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YifanDengWHU/META-DDIE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YifanDengWHU/META-DDIE] 你好，我运行代码的时候出现了这个错误：FileNotFoundError: [Errno 2] No such file or directory: 'models1005/model_nn_5ways_1shot4mag1001722seen.pkl'，请问是怎么一回事呢？ (Issue #2)





 
你好，应该是在读模型的时候产生了问题，你看一下具体是在哪一行的时候产生的问题呢？路径下面有这个名字的模型嘛？

**Comment by nancy-ux** [comment]
Traceback (most recent call last):
  File "main.py", line 395, in <module>    
    main()
  File "main.py", line 325, in main        
    torch.save(model_nn.state_dict(), str( 
  File "D:\Anaconda_Package\lib\site-packages\torch\serialization.py", line 377, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "D:\Anaconda_Package\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)  File "D:\Anaconda_Package\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models1005/model_nn_5ways_1shot4mag1001722seen.pkl'

**Comment by YifanDengWHU** [comment]
这里是因为你没有models1005这个文件夹，所以保存模型的时候失败了，你可以把models1005都删掉

**Comment by nancy-ux** [comment]
请问是在哪里删呀？删掉后对跑出来的精度影响大吗？

**Comment by YifanDengWHU** [comment]
你好，你可以把main.py中出现的所有models1005/都删除，不会有影响

**Comment by nancy-ux** [comment]
解决啦 ，谢谢你！非常感谢！！！
